baseurl = "" # Hostname (and path) to the root, e.g. https://www.highbluffcap.com/
title = "Private Equity Firms & Private Equity | High Bluff Capital"
theme = "hugo-universal-theme"
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

# Define the number of posts per page
paginate = 10

[menu]

# Main menu

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Team"
    url = "/team"
    weight = 2

[[menu.main]]
    name = "Investment Approach"
    url = "/investment-approach/"
    weight = 3

[[menu.main]]
    name = "Portfolio"
    url = "/portfolio"
    weight = 4

[[menu.main]]
    name = "News"
    url = "/news/"
    weight = 5

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 6

# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "GitHub"
    url = "https://github.com/devcows/hugo-universal-theme"
    pre = "<i class='fa fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 2
    name = "Facebook"
    url = "http://facebook.com"
    pre = "<i class='fa fa-2x fa-facebook'></i>"

[[menu.topbar]]
    weight = 3
    name = "Twitter"
    url = "http://twitter.com"
    pre = "<i class='fa fa-2x fa-twitter'></i>"

[[menu.topbar]]
    weight = 4
    name = "Email"
    url = "mailto:your@email.com"
    pre = "<i class='fa fa-2x fa-envelope'></i>"

[params]
    viewMorePostLink = "/news/"
    author = "High Bluff Capital Partners"
    defaultKeywords = ["investment firm san diego", "san diego investment firm", "high bluff capital"]
    defaultDescription = "High Bluff Capital is a private equity firm based in San Diego, CA that focuses on control oriented equity investments in consumer facing companies. Click here to learn more."

    # Google Maps API key (if not set will default to not passing a key.)
    googleMapsApiKey = "AIzaSyCP1mLtPMCM_3_y6hf7uzbSmsutlpNKNFM"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "default"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io email
    # email = "your@email.com"

    about_us = "<p>High Bluff Capital is based in San Diego, California and is the private investment firm founded by Anand Gowda. The firm’s focus is on making control-oriented equity investments in consumer-facing companies.</p>"
    copyright = "Copyright (c) 2018, High Bluff Capital Partners; all rights reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    logo = "https://res.cloudinary.com/zheisey/image/upload/c_scale,w_180/v1538932713/high-bluff-capital/high-bluff-logo.png"
    logo_small = "https://res.cloudinary.com/zheisey/image/upload/c_scale,w_140/v1538932713/high-bluff-capital/high-bluff-logo.png"
    address = """<p><strong>High Bluff Capital Partners</strong>
        <br>12760 High Bluff Drive
        <br>Suite 310
        <br>San Diego, CA 92130
      </p>
      """

[Permalinks]
    blog = "/news/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = false
    text = """<p class="hidden-sm hidden-xs">Contact us on +420 777 555 333 or hello@universal.com.</p>
      <p class="hidden-md hidden-lg"><a href="#" data-animate-hover="pulse"><i class="fa fa-phone"></i></a>
      <a href="#" data-animate-hover="pulse"><i class="fa fa-envelope"></i></a>
      </p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carousel]
    enable = true
    # All carousel items are defined in their own files. You can find example items
    # at '/data/carousel'.
    # For more informtion take a look at the README.

[params.expertise]
    enable = true
    # All specialties are defined in their own files. You can find example items
    # at '/data/expertise'.
    # For more informtion take a look at the README.

[params.testimonials]
    enable = false
    # All testimonials are defined in their own files. You can find example items
    # at '/data/testimonials'.
    # For more informtion take a look at the README.
    title = "Testimonials"
    subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."

[params.read_blog]
    enable = true
    icon = "fas fa-dollar-sign"
    title = "Want the Latest Investment News & Info?"
    subtitle = "This is ground zero for company updates, industry tips & best practices, and recent happenings in the investment world."
    link_url = "/new/"
    link_text = "Get the Latest News from High Bluff Capital"

[params.clients]
    enable = true
    # All clients are defined in their own files. You can find example items
    # at '/data/clients'.
    # For more informtion take a look at the README.
    title = "Our Portfolio"
    subtitle = "These are Just a Few of the Companies in Our Investment Portfolio"

[params.recent_posts]
    enable = false
    title = "From our blog"
    subtitle = "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo."
